version: '3'
services:
  backend:
    build: ./giflink-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./giflink-backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build: ./giflink-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./giflink-frontend:/usr/src/app
