version: '3'
services:
  backend:
    build: ./giftlink-backend
    ports:
      - "3000:3000"  # Expose backend on port 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=${MONGO_URL}  # Use MongoDB connection string from .env
      - JWT_SECRET=${JWT_SECRET}  # Use JWT secret from .env
    depends_on:
      - frontend

  frontend:
    build: ./giftlink-frontend
    ports:
      - "80:80"  # Expose frontend on port 80
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost:3000  # Update to match the backend port
