version: '3'
services:
  backend:
    build: ./giftlink-backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./giftlink-backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build: ./giftlink-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./giftlink-frontend:/usr/src/app